### ISSUE TITLE
Failed to get message from source. Skip it.

### ISSUE THREAD

**Issue by axelaris** [otokarev/logstash-output-cassandra#2]
Hi.
I've tried to configure logs output to **Cassandra** in parallel with **Elasticsearch** (which is working perfectly). Here is my output plugin configuration:

```
    cassandra {
   username => "bla-bla"
   password => "bla-bla-bla"
   hosts => ["192.168.x.y"]
   keyspace => "logs"
   table => "query_log"
   consistency => "all"
   source => "@message"
   ignore_bad_messages => true
   }
```

When I applied this configuration, my stdout logs starts to grow very quickly with messages like **"Failed to get message from source. Skip it"**, followed by full message dump. The most strange part, the size of message dump is about **40x** times more than original message!

For debug reasons, I've enabled "stdout" output plugin, and recorded plain log messages in parallel. Please take a look at the same log messages received by two output plugins.
Stdout plugin: http://pastebin.com/nhef8vyC
Cassandra output plugin: http://pastebin.com/mB3wQAte

Could you please help me to understand what's wrong with plugin there? Or did I miss something in configuration?
Thanks.

**Comment by otokarev** [comment]
Hi Alexey,

> source => "@message"

```
           "@message" => "{\"cf_app_id\":\"e621b083-e46d-4984-a779-6219665ea0ec\",\"cf_app_name\":\"LogGenerator\",\"cf_org_id\":\"9d65b157-8a9e-42ec-8320-32c47a591aa6\",\"cf_org_name\":\"hospira\",\"cf_space_id\":\"b9a69f52-4f04-49e2-97c0-825ef5c58aca\",\"cf_space_name\":\"dev\",\"event_type\":\"LogMessage\",\"level\":\"info\",\"message_type\":\"OUT\",\"msg\":\"09:19:55,033  INFO LogGenerator: - appId: 1188 Test message : 95\",\"origin\":\"dea_logging_agent\",\"source_instance\":\"0\",\"source_type\":\"App\",\"time\":\"2015-08-13T09:19:55Z\",\"timestamp\":1439457595033994947}",
```

but it will not work, the plugin has nothing to do with strings, if it is a json encoded data it must be parsed (json filter might help).

For example:

for _source => "message"_ the valid format of input data will be (stdout plugin output):

```
{
       "message" => {
                "id" => "216533602",
                "at" => "2015-05-08 10:24:22",
          "duration" => "0.0026",
        "resellerId" => "0",
                "ip" => "149.62.180.252",
               "cmd" => "retrieveResellerRequest",
             .....
             "value" => "a:0:{}",
               "md5" => "d4184593e9f5277b8d0981c78a3ba303",
               "src" => "rcp",
              "date" => "2015-05-08"
    },
      "@version" => "1",
    "@timestamp" => "2015-08-13T17:10:00.749Z",
          "host" => "cassandra-cluster-master.st001.openprovider.nl"
}
```

**Comment by otokarev** [comment]
<continue>

> When I applied this configuration, my stdout logs starts to grow very quickly with messages like "Failed to get message from source. Skip it", followed by full message dump. The most strange part, the size of message dump is about 40x times more than original message!

If you about http://pastebin.com/mB3wQAte, then i noticed that this log contains syslog specific things like: "syslog_facility", "syslog_severity" strings. I'd say there is something in logstash that could interfere with your test configurations, probably there were other configs loaded from /etc/logstash/conf.d/

> "Failed to get message from source. Skip it"
> This message means that data pointed to by "source" has wrong format. For example, it is a json encoded string.

Oleg

**Comment by axelaris** [comment]
Thanks for your help.
I was managed to configure the plugin properly. Now it's works.
